import type { EntityStats } from './Entity';

export const Cards: Record<string, EntityStats> = {
    knight: {
        id: 'knight',
        name: 'Knight',
        type: 'troop',
        hp: 1666,
        damage: 202,
        hitSpeed: 1.2,
        loadTime: 0.7,
        speed: 1.0, // Medium
        range: 0.8, // Melee
        sightRange: 5.5,
        radius: 0.5,
        mass: 6,
        isAir: false,
        targetType: 'ground'
    },
    archers: {
        id: 'archers',
        name: 'Archers',
        type: 'troop',
        hp: 304,
        damage: 107,
        hitSpeed: 0.9,
        loadTime: 1.1,
        speed: 1.0, // Medium
        range: 5.0,
        sightRange: 5.5,
        radius: 0.5,
        mass: 3,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 10,
        spawnCount: 2,
        spawnRadius: 0.8
    },
    giant: {
        id: 'giant',
        name: 'Giant',
        type: 'troop',
        hp: 4091,
        damage: 254,
        hitSpeed: 1.5,
        loadTime: 1.0,
        speed: 0.75, // Slow
        range: 0.8,
        sightRange: 5.5,
        radius: 0.75,
        mass: 18,
        isAir: false,
        targetType: 'building',
        isBuildingTargeter: true
    },
    pekka: {
        id: 'pekka',
        name: 'P.E.K.K.A',
        type: 'troop',
        hp: 3760,
        damage: 816,
        hitSpeed: 1.8,
        loadTime: 1.3,
        speed: 0.75, // Slow
        range: 0.8,
        sightRange: 5.5,
        radius: 0.8,
        mass: 18,
        isAir: false,
        targetType: 'ground'
    },
    musketeer: {
        id: 'musketeer',
        name: 'Musketeer',
        type: 'troop',
        hp: 720,
        damage: 218,
        hitSpeed: 1.1,
        loadTime: 0.6,
        speed: 1.0, // Medium
        range: 6.0,
        sightRange: 6.0,
        radius: 0.5,
        mass: 4,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 10
    },
    hog_rider: {
        id: 'hog_rider',
        name: 'Hog Rider',
        type: 'troop',
        hp: 1696,
        damage: 318,
        hitSpeed: 1.6,
        loadTime: 1.0,
        speed: 2.0, // Very Fast
        range: 0.8,
        sightRange: 5.5,
        radius: 0.6,
        mass: 8,
        isAir: false,
        targetType: 'building',
        isBuildingTargeter: true,
        jumpsRiver: true
    },
    skeletons: {
        id: 'skeletons',
        name: 'Skeletons',
        type: 'troop',
        hp: 81,
        damage: 81,
        hitSpeed: 1.0,
        loadTime: 0.5,
        speed: 1.5, // Fast
        range: 0.8,
        sightRange: 5.5,
        radius: 0.4,
        mass: 1,
        isAir: false,
        targetType: 'ground',
        spawnCount: 3,
        spawnRadius: 0.5
    },
    barbarians: {
        id: 'barbarians',
        name: 'Barbarians',
        type: 'troop',
        hp: 670,
        damage: 191,
        hitSpeed: 1.4,
        loadTime: 1.0,
        speed: 1.0, // Medium
        range: 0.8,
        sightRange: 5.5,
        radius: 0.5,
        mass: 4,
        isAir: false,
        targetType: 'ground',
        spawnCount: 5,
        spawnRadius: 1.0
    },
    minions: {
        id: 'minions',
        name: 'Minions',
        type: 'troop',
        hp: 230,
        damage: 105,
        hitSpeed: 1.0,
        loadTime: 1.0,
        speed: 1.5, // Fast
        range: 1.5,
        sightRange: 5.5,
        radius: 0.4,
        mass: 2,
        isAir: true,
        targetType: 'all',
        spawnCount: 3,
        spawnRadius: 0.8
    },
    wizard: {
        id: 'wizard',
        name: 'Wizard',
        type: 'troop',
        hp: 720,
        damage: 281,
        hitSpeed: 1.4,
        loadTime: 1.0,
        speed: 1.0, // Medium
        range: 5.5,
        sightRange: 6.0,
        radius: 0.5,
        mass: 4,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 10
    },
    princess: {
        id: 'princess',
        name: 'Princess',
        type: 'troop',
        hp: 261,
        damage: 169,
        hitSpeed: 3.0,
        loadTime: 1.0,
        speed: 1.0, // Medium
        range: 9.0,
        sightRange: 9.5,
        radius: 0.4,
        mass: 2,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 10
    },
    princess_tower: {
        id: 'princess_tower',
        name: 'Princess Tower',
        type: 'tower',
        hp: 2534,
        damage: 90,
        hitSpeed: 0.8,
        loadTime: 0.5,
        speed: 0,
        range: 7.5,
        sightRange: 7.5,
        radius: 1.5,
        mass: Infinity,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 10
    },
    king_tower: {
        id: 'king_tower',
        name: 'King Tower',
        type: 'tower',
        hp: 4008,
        damage: 90,
        hitSpeed: 1.0,
        loadTime: 0.2,
        speed: 0,
        range: 7.0,
        sightRange: 7.0,
        radius: 2.0,
        mass: Infinity,
        isAir: false,
        targetType: 'all',
        projectileSpeed: 15
    }
};
